name: Lint and Test

on:
  push:
    branches: 
      - dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
