name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          REACT_APP_PUBLIC_URL: ${{ secrets.REACT_APP_PUBLIC_URL }}
      - name: Archive Development Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
